security:

    encoders:
        AppBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User:
                    algorithm: bcrypt
                    cost: 12

    providers:
        chain_provider:
                chain:
                    providers: [our_users]
        our_users:
                  entity: {class: AppBundle\Entity\User, property: email}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticator:
                   - app.security.login_form_authenticator
                   - app.security.facebook_authenticator
                   - AppBundle\Security\JwtTokenAuthenticator
                entry_point: app.security.login_form_authenticator

            logout:
              path: /logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
